language: c
sudo: false

before_script:
  - bash ./build_libmicrohttpd.sh --compile

script:
  - mkdir build ; cd build ; cmake ../ ; make

env:
  - PKG_CONFIG_PATH="/tmp/libmicrohttpd_install/lib/pkgconfig/"

addons:
  apt:
    packages:
      - astyle
