language: c
sudo: false

before_script:
  - bash ./build_libmicrohttpd.sh --compile

script:
 - mkdir build ; cd build ; cmake ../ ; make

env:
  - CMAKE_C_FLAGS="-I/tmp/libmicrohttpd_install/include" CMAKE_LD_FLAGS="-L/tmp/libmicrohttpd_install/lib"

addons:
  apt:
    packages:
      - astyle
